### ISSUE TITLE
Metropolis Hastings trial distribution

### ISSUE THREAD

**Issue by laserlab** [ubsuny/CompPhys#35]
While reimplementing the metropolis Hastings algorithm in Tensorflow the data in the Jupiter notebook cannot be reproduced if a normal distribution is used for the trial step.

Possible reason is the following line:

https://github.com/ubsuny/CompPhys/blob/7ae65dc1ba754c8b6addd8fbde3f7beff4f00523/RandomNumbers/metropolis.h#L31

which is unclear to me why to use the same distribution for the trial as for the walker. In particular since in general this should be a symmetric distribution.

**Comment by rappoccio** [comment]
I'm not sure I follow. The distribution is symmetric. Here `a1` is a uniform deviate between +-1. Do you mean that this distribution should be Gaussian and not uniform? I'm not sure it will change the final distribution, although perhaps it could change the convergence rate.
